### ISSUE TITLE
How do you know the "sys_call_table" symbol last exported  in 5.6.19.  Thanks.

### ISSUE THREAD

**Issue by wangzhangjun** [NoviceLive/research-rootkit#8]
How do you know the "sys_call_table" symbol last exported  in 5.6.19.  
https://elixir.bootlin.com/linux/v5.6.19/source/kernel/kallsyms.c  Where can I see from this code? Thnaks

**Comment by wangzhangjun** [comment]
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=0bd476e6c67190b5eb7b6e105c8db8ff61103281

From this patch , we can know. Thanks.

**Comment by NoviceLive** [comment]
Close as he figured out.
